import { defineConfig } from 'oxfmt';

export default defineConfig({
  arrowParens: 'avoid',
  ignorePatterns: [
    'node_modules',
    'pnpm-lock.yaml',
    'dist',
    'coverage',
    '.angular',
    '.env',
    '.env.*',
    '.vscode',
    '.idea',
    '*.swp',
    '*.swo',
    '*~',
    '.DS_Store',
    'Thumbs.db',
    'documentation.json',
    '*.tsbuildinfo',
    '*.tgz',
    '*.log',
    'npm-debug.log*',
    'pnpm-debug.log*',
    'yarn-debug.log*',
    'yarn-error.log*',
    'test-results',
    'playwright-report',
    'storybook-static',
    'package-lock.json',
    'yarn.lock',
    'CHANGELOG.md',
    '.github',
    '.oxfmtrc.json',
    '.oxlintrc.json',
    '.storybook/tsconfig.json',
    'README.md',
    '*.yml',
    '*.config.mjs',
    'angular.json',
    'projects/**/*.json',
    'tsconfig.node.json',
    '.agents/*'
  ],
  jsdoc: true,
  printWidth: 100,
  singleQuote: true,
  sortImports: {
    groups: [
      ['side_effect', 'side_effect_style'],
      'builtin',
      'external',
      ['internal', 'subpath'],
      ['parent', 'sibling', 'index'],
      'style',
      'unknown'
    ],
    internalPattern: ['@dragone/'],
    newlinesBetween: true,
    order: 'asc',
    partitionByComment: false,
    partitionByNewline: false,
    sortSideEffects: false
  },
  sortPackageJson: true,
  trailingComma: 'none'
});
