import { defineConfig } from 'oxlint';

export default defineConfig({
  categories: {
    correctness: 'error',
    perf: 'warn',
  },
  env: {
    browser: true,
    es2024: true,
    node: true,
    'shared-node-browser': true,
  },
  ignorePatterns: ['**/dist', '**/out-tsc', '**/node_modules', '**/coverage'],
  overrides: [
    {
      files: ['**/*.ts', '**/*.cts', '**/*.mts', '**/*.js', '**/*.cjs', '**/*.mjs'],
      rules: {
        // TypeScript
        'typescript-eslint/no-duplicate-enum-values': 'error',
        'typescript-eslint/no-empty-interface': 'error',
        'typescript-eslint/no-empty-object-type': 'error',
        'typescript-eslint/no-explicit-any': 'warn',
        'typescript-eslint/no-extra-non-null-assertion': 'error',
        'typescript-eslint/no-inferrable-types': 'error',
        'typescript-eslint/no-misused-new': 'error',
        'typescript-eslint/no-namespace': 'error',
        'typescript-eslint/no-non-null-asserted-optional-chain': 'error',
        'typescript-eslint/no-non-null-assertion': 'warn',
        'typescript-eslint/no-this-alias': 'error',
        'typescript-eslint/no-unnecessary-type-constraint': 'error',
        'typescript-eslint/no-unsafe-declaration-merging': 'error',
        'typescript-eslint/no-unsafe-function-type': 'error',
        'typescript-eslint/no-wrapper-object-types': 'error',
        'typescript-eslint/prefer-as-const': 'error',
        'typescript-eslint/prefer-namespace-keyword': 'error',
        'typescript-eslint/triple-slash-reference': 'error',
        'typescript/ban-ts-comment': 'error',
        'typescript/adjacent-overload-signatures': 'error',
        // Eslint
        'for-direction': 'error',
        'init-declarations': ['error', 'never'],
        'import/consistent-type-specifier-style': ['error', 'prefer-inline'],
        'no-array-constructor': 'error',
        'no-async-promise-executor': 'error',
        'no-case-declarations': 'error',
        'no-compare-neg-zero': 'error',
        'no-cond-assign': 'error',
        'no-constant-binary-expression': 'error',
        'no-constant-condition': 'error',
        'no-control-regex': 'error',
        'no-debugger': 'error',
        'no-delete-var': 'error',
        'no-dupe-else-if': 'error',
        'no-duplicate-case': 'error',
        'no-empty': 'error',
        'no-empty-character-class': 'error',
        'no-empty-function': 'error',
        'no-empty-pattern': 'error',
        'no-empty-static-block': 'error',
        'no-ex-assign': 'error',
        'no-extra-boolean-cast': 'error',
        'no-fallthrough': 'error',
        'no-global-assign': 'error',
        'no-invalid-regexp': 'error',
        'no-irregular-whitespace': 'error',
        'no-loss-of-precision': 'error',
        'no-misleading-character-class': 'error',
        'no-nonoctal-decimal-escape': 'error',
        'no-prototype-builtins': 'error',
        'no-regex-spaces': 'error',
        'no-self-assign': 'error',
        'no-shadow-restricted-names': 'error',
        'no-sparse-arrays': 'error',
        'no-unsafe-finally': 'error',
        'no-unsafe-optional-chaining': 'error',
        'no-unused-expressions': 'error',
        'no-unused-labels': 'error',
        'no-unused-private-class-members': 'error',
        'no-unused-vars': [
          'error',
          {
            args: 'all',
            argsIgnorePattern: '^_',
            caughtErrors: 'all',
            caughtErrorsIgnorePattern: '^_',
            destructuredArrayIgnorePattern: '^_',
            ignoreRestSiblings: true,
            varsIgnorePattern: '^_',
          },
        ],
        'no-useless-backreference': 'error',
        'no-useless-catch': 'error',
        'no-useless-escape': ['error', { allowRegexCharacters: ['\\', '.'] }],
        'no-var': 'error',
        'prefer-const': 'error',
        'prefer-rest-params': 'error',
        'prefer-spread': 'error',
        'require-yield': 'error',
        'sort-imports': 'off',
        'use-isnan': 'error',
        'valid-typeof': 'error',
      },
    },
    {
      files: ['**/*.spec.ts', '**/*.test.ts'],
      rules: {
        'vitest/expect-expect': 'error',
        'vitest/no-commented-out-tests': 'warn',
        'vitest/no-conditional-expect': 'error',
        'vitest/no-disabled-tests': 'warn',
        'vitest/no-focused-tests': 'error',
        'vitest/no-identical-title': 'error',
        'vitest/no-import-node-test': 'error',
        'vitest/no-standalone-expect': 'error',
        'vitest/prefer-hooks-in-order': 'warn',
        'vitest/prefer-hooks-on-top': 'warn',
        'vitest/prefer-to-be': 'warn',
        'vitest/prefer-to-contain': 'warn',
        'vitest/prefer-to-have-length': 'warn',
        'vitest/valid-describe-callback': 'off',
        'vitest/valid-expect': 'error',
        'vitest/valid-title': 'error',
        'vitest/prefer-describe-function-title': 'error',
      },
    },
  ],
  plugins: ['typescript', 'vitest', 'eslint', 'oxc'],
});
