allowBuilds:
  '@compodoc/compodoc': true
  '@parcel/watcher': true
  esbuild: true
  lefthook: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAge: 1440
minimumReleaseAgeStrict: false
ovverides:
  '@analogjs/vite-plugin-angular@2.5.2>@angular/build': '$@angular/build'
  '@analogjs/vite-plugin-angular@2.5.2>@angular-devkit/build-angular': '-'
  '@storybook/angular@10.4.1>typescript': '$typescript'
patchedDependencies:
  ng-primitives: patches/ng-primitives.patch
